### ISSUE TITLE
Console log should be ereased

### ISSUE THREAD

**Issue by Shadowrunner11** [vitalspace/admin-dashboard-analytics-ux#1]
https://github.com/vitalspace/Admin-dashboard-analytics-UX/blob/c4fb8641a6574a26a561bf188eef882825a69530/src/App.svelte#L2C13-L2C13

**Comment by vitalspace** [comment]
Nope, es una marca que dejó en mis proyectos en svelte.

**Comment by Shadowrunner11** [comment]
> Nope, es una marca que dejó en mis proyectos en svelte.

If that is the case, should consider using a logger instead of console.log and as well specify code style guide as a governance asset

**Comment by vitalspace** [comment]
> > Nope, es una marca que dejó en mis proyectos en svelte.
> 
> If that is the case, should consider using a logger instead of console.log and as well specify code style guide as a governance asset

Let the interested user fork the code and do what he wants with it.
